blog.user-username=ilham
blog.user-password=$2y$10$NP3xuI3p.ndkbUivZcoaQeMGF5kTvsBffrL1UK25dsw5ASUJ0CwwG

blog.jwt-iss=https://google.com
blog.jwt-secretKey=8VETUoDBjrbK0vtTGOhV9XLEUPSOS25qk3UaiQgOXfc0KuiM